-- AlterEnum: Add WARRANTY_EXPIRED and MAINTENANCE_DUE_SOON to NotificationType
ALTER TYPE "NotificationType" ADD VALUE 'WARRANTY_EXPIRED';
ALTER TYPE "NotificationType" ADD VALUE 'MAINTENANCE_DUE_SOON';
